### ISSUE TITLE
pgp_secretstore should warn if running as root

### ISSUE THREAD

**Issue by jdreichmann** [famedly/ansible-collection-base#199]
It is easy to mess up and get strange issues when `become: true` is used in a playbook, as root usually has neither keyring nor access to any gpg-agents or similar. For this reason, the module should warn when it's run as root, as it is trivial to detect in python.

**Comment by jdreichmann** [comment]
```
TASK [famedly.base.gpg_secretstore] ********************************************************************************
[...]
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/module_utils/gpg_utils.py", line 171, in get_recipients_from_encrypted_file
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/transcaffeine/.ansible/tmp/ansible-tmp-1704191452.873856-324166-118803547824027/AnsiballZ_gpg_secretstore.py", line 107, in <module>
    _ansiballz_main()
  File "/home/transcaffeine/.ansible/tmp/ansible-tmp-1704191452.873856-324166-118803547824027/AnsiballZ_gpg_secretstore.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/transcaffeine/.ansible/tmp/ansible-tmp-1704191452.873856-324166-118803547824027/AnsiballZ_gpg_secretstore.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.famedly.base.plugins.modules.gpg_secretstore', init_globals=dict(_module_fqn='ansible_collections.famedly.base.plugins.modules.gpg_secretstore', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/modules/gpg_secretstore.py", line 517, in <module>
  File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/modules/gpg_secretstore.py", line 404, in main
  File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/module_utils/gpg_utils.py", line 174, in get_recipients_from_encrypted_file
ansible_collections.famedly.base.plugins.module_utils.gpg_utils.GPGException: Subkey 112CED6FF8C78971 has no known associated keys
fatal: [famedly.de -> localhost]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/module_utils/gpg_utils.py", line 171, in get_recipients_from_encrypted_file
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/transcaffeine/.ansible/tmp/ansible-tmp-1704191452.873856-324166-118803547824027/AnsiballZ_gpg_secretstore.py", line 107, in <module>
        _ansiballz_main()
      File "/home/transcaffeine/.ansible/tmp/ansible-tmp-1704191452.873856-324166-118803547824027/AnsiballZ_gpg_secretstore.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/transcaffeine/.ansible/tmp/ansible-tmp-1704191452.873856-324166-118803547824027/AnsiballZ_gpg_secretstore.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.famedly.base.plugins.modules.gpg_secretstore', init_globals=dict(_module_fqn='ansible_collections.famedly.base.plugins.modules.gpg_secretstore', _modlib_path=modlib_path),
      File "<frozen runpy>", line 226, in run_module
      File "<frozen runpy>", line 98, in _run_module_code
      File "<frozen runpy>", line 88, in _run_code
      File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/modules/gpg_secretstore.py", line 517, in <module>
      File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/modules/gpg_secretstore.py", line 404, in main
      File "/tmp/ansible_famedly.base.gpg_secretstore_payload_c7sp9g75/ansible_famedly.base.gpg_secretstore_payload.zip/ansible_collections/famedly/base/plugins/module_utils/gpg_utils.py", line 174, in get_recipients_from_encrypted_file
    ansible_collections.famedly.base.plugins.module_utils.gpg_utils.GPGException: Subkey 112CED6FF8C78971 has no known associated keys
  module_stdout: |-
    warn: running as uid 0 (root), ensure the correct gnupg keyring is loaded
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
  ```
  Output - in `module_stdout` is the warning about running as root, in `module_stderr` is the `GPGException` about the subkey not being known.
